server:
    port: 8080
#spring config
spring:
    profiles:
       active: dev
       default: dev
    liveBeansView:
      mbeanDomain: dev
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
    mvc:
        favicon:
            enabled: false
    http:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 120MB
    aop:
      auto: true
      proxyTargetClass: false
    jndi:
      ignore: true

# MyBatis
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    config: classpath:config/mybatis-config.xml
#    dynamic-datasource: true  #启用mybatis动态数据源
zxwl:
    app:
      name: test
      version: 1.0.0.0
      comment: test
